gleans frontend spec from dkan module

diff --git a/commands/web/dkan-frontend-install b/commands/web/dkan-frontend-install
--- a/commands/web/dkan-frontend-install
+++ b/commands/web/dkan-frontend-install
@@ -14,17 +14,28 @@ FRONTEND_VCS_URL='https://github.com/GetDKAN/data-catalog-app/'
 FRONTEND_VCS_REF='no-node-sass'
 FRONTEND_THEME='dkan_js_frontend_bartik'
 
-# TODO: Replace this with a Composer-based dependency.
-
 if [[ -L $FRONTEND_DOCROOT_DIR ]]; then
   echo "ERROR: Symlink $FRONTEND_DOCROOT_DIR already exists."
   exit 1
 fi
 
 #if [ -d $FRONTEND_DIR ]; then
- # echo "ERROR: Frontend $FRONTEND_DIR already exists."
-  #exit 1
+# echo "ERROR: Frontend $FRONTEND_DIR already exists."
+#exit 1
 #fi
+
+# Glean frontend spec from dkan module.
+DKAN_MODULE_PATH=$(composer show --format=json getdkan/dkan | jq -r '.path')
+if [ ! -z "$DKAN_MODULE_PATH" ]; then
+  DKAN_MODULE_EXTRA=$(composer config extra -d $DKAN_MODULE_PATH)
+  if [ ! -z "$DKAN_MODULE_EXTRA" ]; then
+    DKAN_FRONTEND_CONFIG=$(jq '."dkan-fronten"' <<<$DKAN_MODULE_EXTRA)
+    if [ ! -z "$DKAN_FRONTEND_CONFIG" ]; then
+      FRONTEND_VCS_REF=$(jq -r --arg DEFAULT "$FRONTEND_VCS_REF" '."ref" // $DEFAULT' <<< $DKAN_FRONTEND_CONFIG)
+      FRONTEND_VCS_URL=$(jq -r --arg DEFAULT "$FRONTEND_VCS_URL" '."url" // $DEFAULT' <<< $DKAN_FRONTEND_CONFIG)
+    fi
+  fi
+fi
 
 composer require getdkan/$FRONTEND_THEME
 drush theme:enable $FRONTEND_THEME
@@ -32,26 +43,12 @@ drush config-set system.theme default $FRONTEND_THEME -y
 
 drush pm-enable dkan_js_frontend -y
 
-# TODO: Glean frontend ref info from dkan module.
-DKAN_MODULE_PATH=$(composer show --format=json getdkan/dkan | jq -r '.path')
-echo $DKAN_MODULE_PATH
-#cd $DKAN_MODULE_PATH
-#composer config extra.dkan-frontend
-DKAN_FRONTEND_CONFIG=$(composer config extra.dkan-frontend)
-echo $DKAN_FRONTEND_CONFIG
-#if [ ! -z $DKAN_FRONTEND_CONFIG ]; then
-#  echo $DKAN_FRONTEND_CONFIG | jq -r '.url'
-#fi
-
-#composer show --format=json getdkan/dkan | jq -r '.path'
-
-# cd docroot/modules/contrib/dkan
-# composer config extra | jq .
+echo " ** Gathering frontend application: $FRONTEND_VCS_REF from $FRONTEND_VCS_URL"
 
 mkdir -p $FRONTEND_TMP
 wget -O $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip "$FRONTEND_VCS_URL"archive/$FRONTEND_VCS_REF.zip
 unzip $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip -d docroot/
-mv docroot/data-catalog-app-$FRONTEND_VCS_REF docroot/frontend
+mv docroot/data-catalog-app-$FRONTEND_VCS_REF "$FRONTEND_DOCROOT_DIR"
 
 #ln -s $PWD/$FRONTEND_DIR $FRONTEND_DOCROOT_DIR
 
