update from 10258

diff --git a/commands/web/dkan-frontend-install b/commands/web/dkan-frontend-install
--- a/commands/web/dkan-frontend-install
+++ b/commands/web/dkan-frontend-install
@@ -5,6 +5,7 @@
 ## Usage: dkan-frontend-install
 
 FRONTEND_TMP='src/tmp'
+FRONTEND_DIR='src/frontend'
 FRONTEND_DOCROOT_DIR='docroot/frontend'
 FRONTEND_VCS_URL='https://github.com/GetDKAN/data-catalog-app/'
 # TODO: no-node-sass is the known-good branch, so we should move that forward to be a release.
@@ -13,28 +14,45 @@ FRONTEND_VCS_URL='https://github.com/GetDKAN/data-catalog-app/'
 FRONTEND_VCS_REF='no-node-sass'
 FRONTEND_THEME='dkan_js_frontend_bartik'
 
-# TODO: Replace this with a Composer-based dependency.
-
 if [[ -L $FRONTEND_DOCROOT_DIR ]]; then
   echo "ERROR: Symlink $FRONTEND_DOCROOT_DIR already exists."
   exit 1
+fi
+
+#if [ -d $FRONTEND_DIR ]; then
+# echo "ERROR: Frontend $FRONTEND_DIR already exists."
+#exit 1
+#fi
+
+# Glean frontend spec from dkan module.
+DKAN_MODULE_PATH=$(composer show --format=json getdkan/dkan | jq -r '.path')
+if [ ! -z "$DKAN_MODULE_PATH" ]; then
+  DKAN_MODULE_EXTRA=$(composer config extra -d $DKAN_MODULE_PATH)
+  if [ ! -z "$DKAN_MODULE_EXTRA" ]; then
+    DKAN_FRONTEND_CONFIG=$(jq '."dkan-fronten"' <<<$DKAN_MODULE_EXTRA)
+    if [ ! -z "$DKAN_FRONTEND_CONFIG" ]; then
+      FRONTEND_VCS_REF=$(jq -r --arg DEFAULT "$FRONTEND_VCS_REF" '."ref" // $DEFAULT' <<< $DKAN_FRONTEND_CONFIG)
+      FRONTEND_VCS_URL=$(jq -r --arg DEFAULT "$FRONTEND_VCS_URL" '."url" // $DEFAULT' <<< $DKAN_FRONTEND_CONFIG)
+    fi
+  fi
 fi
 
 composer require getdkan/$FRONTEND_THEME
 drush theme:enable $FRONTEND_THEME
 drush config-set system.theme default $FRONTEND_THEME -y
 
-# TODO: Glean frontend ref info from dkan module.
-# cd docroot/modules/contrib/dkan
-# composer config extra | jq .
+drush pm-enable dkan_js_frontend -y
+
+echo " ** Gathering frontend application: $FRONTEND_VCS_REF from $FRONTEND_VCS_URL"
 
 mkdir -p $FRONTEND_TMP
 wget -O $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip "$FRONTEND_VCS_URL"archive/$FRONTEND_VCS_REF.zip
 unzip $FRONTEND_TMP/data-catalog-app-$FRONTEND_VCS_REF.zip -d docroot/
-mv docroot/data-catalog-app-$FRONTEND_VCS_REF docroot/frontend
-rm -rf $FRONTEND_TMP
+mv docroot/data-catalog-app-$FRONTEND_VCS_REF "$FRONTEND_DOCROOT_DIR"
 
-cd $FRONTEND_DOCROOT_DIR || exit 1
+#ln -s $PWD/$FRONTEND_DIR $FRONTEND_DOCROOT_DIR
+
+cd $FRONTEND_DOCROOT_DIR || exit
 # Don't fill the screen with warnings, only errors.
 # TODO: Make sure we don't miss important warnings.
 npm --loglevel=error install
